# Generated by Django 3.2.5 on 2021-07-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_auto_20210624_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('cuartos', models.CharField(max_length=30)),
                ('pisos', models.CharField(max_length=30)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='administrativo.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=30)),
                ('cuartos', models.CharField(max_length=30)),
                ('mensual', models.CharField(max_length=30)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barriosd', to='administrativo.barrio')),
            ],
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Persona',
        ),
        migrations.DeleteModel(
            name='NumeroTelefonico',
        ),
        migrations.AddField(
            model_name='departamentos',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietariosd', to='administrativo.persona'),
        ),
        migrations.AddField(
            model_name='casas',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='administrativo.persona'),
        ),
    ]
